LOAD DATA INFILE 'data/students.csv'
INTO TABLE STUDENT
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA INFILE 'data/courses.csv'
INTO TABLE COURSE
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA INFILE 'data/assessments.csv'
INTO TABLE ASSESSMENT
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA INFILE 'data/student_registration.csv'
INTO TABLE STUDENT_REGISTRATION
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA INFILE 'data/student_assessment.csv'
INTO TABLE STUDENT_ASSESSMENT
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;